-- hyprland.lua
-- Generated by hypr-migrate from: looknfeel.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     6 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.config({
    general = {
        border_size = 0,
        gaps_in = 2,
        gaps_out = 3,
    },
    decoration = {
        rounding = 10,
        rounding_power = 5,
    },
    gesture = "3, vertical, workspace",
})

hl.curve("fluent_decel", {
    type = "bezier",
    points = { 0.05, 0.9, 0.1, 1.1 }
})
hl.curve("easeOutCirc", {
    type = "bezier",
    points = { 0.0, 0.55, 0.45, 1.0 }
})
hl.curve("easeOutCubic", {
    type = "bezier",
    points = { 0.33, 1.0, 0.68, 1.0 }
})
hl.curve("easeinoutsine", {
    type = "bezier",
    points = { 0.37, 0.0, 0.63, 1.0 }
})

hl.layer_rule({ match = { namespace = "match:namespace resolve" }, blur = false })
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.0,
    curve = "fluent_decel",
    style = "slidefadevert 90%",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 2.0,
    curve = "fluent_decel",
    style = "slidefade 10%",
})
